name: Build binaries

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  package:
    name: Package game binaries 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          path: x86_64-unknown-linux-gnu
        - os: macOS-latest
          path: x86_64-apple-darwin
        - os: windows-latest
          path: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: pyoxidizer
    - name: Package binary
      run: pyoxidizer build
    - uses: actions/upload-artifact@v2
      with:
        name: cronenbroguelike-${{ matrix.os }}
        path: build/${{ matrix.path }}/debug/install/*
