name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  package:
    name: Package game binaries 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          path: x86_64-unknown-linux-gnu
        - os: macOS-latest
          path: x86_64-apple-darwin
        - os: windows-latest
          path: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: pyoxidizer
    - name: Package binary
      run: pyoxidizer build
    - name: Zip release contents
      run: tar -czvf release.tar.gz build/${{ matrix.path }}/debug/install/*
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.tar.gz
        asset_name: cronenbroguelike-${{ matrix.os }}.tar.gz
        asset_content_type: application/gzip
